sudo: false
language: python
cache: pip

services:
  - mysql

python:
  - '2.7'
  - '3.6'
  - '3.7-dev'
  - 'pypy3'

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=master

matrix:
  include:
    - { python: '3.6', env: TOXENV=lint }

  exclude:
    - { python: '2.7', env: DJANGO=2.0 }
    - { python: '2.7', env: DJANGO=2.1 }
    - { python: '2.7', env: DJANGO=master }

  allow_failures:
    - env: DJANGO=master

before_install:
  - mysql -e 'CREATE DATABASE atmoiqdb;'

install:
  - travis_retry pip install --upgrade pip tox tox-venv tox-travis

script:
  - tox || travis_terminate 1

notifications:
  email: false
