---
version: '3'

services:
  py36-mysql:
    build:
      context: .
      args:
        IMAGE: 'python:3.6-stretch'
    volumes:
      - .:/app
    links:
      - mysql
    environment:
      TOX_WORK_DIR: /tox
      PYTHON_VERSION: py36
      DATABASE_URL: 'mysql://root:@mysql:3306/atomiqdb'
    command: tox -e py36-django{111,20,21,master}-mysql

  py37-mysql:
    build:
      context: .
      args:
        IMAGE: 'python:3.7-stretch'
    volumes:
      - .:/app
    links:
      - mysql
    environment:
      TOX_WORK_DIR: /tox
      PYTHON_VERSION: py37
      DATABASE_URL: 'mysql://root:@mysql:3306/atomiqdb'
    command: tox -e py36-django{111,20,21,master}-mysql

  pypy3-mysql:
    build:
      context: .
      args:
        IMAGE: 'pypy:3-6-jessie'
    volumes:
      - .:/app
    links:
      - mysql
    environment:
      TOX_WORK_DIR: /tox
      PYTHON_VERSION: pypy3
      DATABASE_URL: 'mysql://root:@mysql:3306/atomiqdb'
    command: tox -e py36-django{111,20,21,master}-mysql

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=atomiqdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  py36-pg:
    build:
      context: .
      args:
        IMAGE: 'python:3.6-stretch'
    volumes:
      - .:/app
    links:
       - postgres
    environment:
      TOX_WORK_DIR: /tox
      PYTHON_VERSION: py36
      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/atomiq-pg'
    command: tox -e py36-django{111,20,21,master}-pg

  py37-pg:
    build:
      context: .
      args:
        IMAGE: 'python:3.7-stretch'
    volumes:
      - .:/app
    links:
       - postgres
    environment:
      TOX_WORK_DIR: /tox
      PYTHON_VERSION: py37
      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/atomiq-pg'
    command: tox -e py36-django{111,20,21,master}-pg

  pypy3-pg:
    build:
      context: .
      args:
        IMAGE: 'pypy:3-6-jessie'
    volumes:
      - .:/app
    links:
       - postgres
    environment:
      TOX_WORK_DIR: /tox
      PYTHON_VERSION: pypy3
      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/atomiq-pg'
    command: tox -e py36-django{111,20,21,master}-pg

  postgres:
    image: postgres:9.6.8
    environment:
      POSTGRES_DB: atomiq-pg




