# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 15:15
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models

import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtomicTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('failed_at', models.DateTimeField(null=True)),
                ('attempted_at', models.DateTimeField(null=True)),
                ('number_of_attempts', models.PositiveIntegerField(default=0)),
                ('visible_after', models.DateTimeField(null=True)),
                ('stacktrace', models.TextField(null=True)),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('processed', 'Processed'), ('failed', 'Failed'), ('deleted', 'Deleted')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CeleryAtomicTask',
            fields=[
                ('atomictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='atomiq.AtomicTask')),
                ('task_name', models.CharField(max_length=256)),
                ('task_arguments', jsonfield.fields.JSONField()),
            ],
            bases=('atomiq.atomictask',),
        ),
        migrations.CreateModel(
            name='SNSAtomicTask',
            fields=[
                ('atomictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='atomiq.AtomicTask')),
                ('topic_arn', models.CharField(max_length=256)),
                ('payload', jsonfield.fields.JSONField()),
            ],
            bases=('atomiq.atomictask',),
        ),
        migrations.CreateModel(
            name='SQSAtomicTask',
            fields=[
                ('atomictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='atomiq.AtomicTask')),
                ('queue_arn', models.CharField(max_length=256)),
                ('payload', jsonfield.fields.JSONField()),
            ],
            bases=('atomiq.atomictask',),
        ),
    ]
